Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClientes.Models
{
    public class Cliente
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El Nombre es Requerido")]
        [MaxLength(80)]
        public string Nombre { get; set; }
        [Required(ErrorMessage ="El Apellido es Requerido")]
        [MaxLength(80)]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "La Direccion es Requerida")]
        [MaxLength(80)]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "La Localidad es Requerida")]
        [MaxLength(80)]
        public string Localidad { get; set; }
        [Required(ErrorMessage = "El Telefono es Requerido")]
        public int Telefono { get; set; }

        [Required(ErrorMessage = "El Email es Requerido")]
        [MaxLength(80)]
        public string Email { get; set; }
   
        public bool Estado { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace MvcClientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Productos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClientes.Models
{
    public class Productos
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "El Nombre del Producto es Requerido")]
        [MaxLength(80)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "La descripcion del Producto es Requerida")]
        [MaxLength(80)]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "La Imagen es requerida")]
    
        public string Imagen { get; set; }
        [Required(ErrorMessage = "Ingrese un monto")]
        
        public int Precio { get; set; }


    }
}

Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcClientes.Data;
using MvcClientes.Models;

namespace MvcClientes.Controllers
{
    public class ClientesController : Controller
    {
        private readonly MvcClientesContext _context;

        public ClientesController(MvcClientesContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cliente.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

 
        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Apellido,Direccion,Localidad,Telefono,Email,Estado")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        //Get para traer los datos para la tabla nueva

       
        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Apellido,Direccion,Localidad,Telefono,Email,Estado")] Cliente cliente)
        {
            if (id != cliente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Cliente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cliente = await _context.Cliente.FindAsync(id);
            _context.Cliente.Remove(cliente);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(int id)
        {
            return _context.Cliente.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcClientes.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcClientes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Clientes/Create.cshtml
@model MvcClientes.Models.Cliente


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="width:100%">
    <div class="col-6">
        <h2 class="text-primary">Agregar Nuevo Cliente</h2>
    </div>
</div>




            <form method="post" enctype="multipart/form-data">
                <div class="modal-body">
                    <div style="padding-left:15%;padding-right:15%;padding-bottom:30px "></div>
                    <div class="row p-3 border-0">
                        <!--si hay un error en el modelo va a salir reflejado en el detalle-->
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    </div>
                    <div class="form-row" style="padding-top:14px;">
                        <div class="form-group col-md-6">
                            <label>Nombres</label>
                            <input asp-for="Nombre" class="form-control" placeholder="Nombres" />
                            <span asp-validation-for="Nombre" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Apellidos</label>
                            <input asp-for="Apellido" class="form-control" placeholder="Apellido" />
                            <span asp-validation-for="Apellido" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-5">
                            <label>Direccion</label>
                            <input asp-for="Direccion" class="form-control" placeholder="Direccion" />
                            <span asp-validation-for="Direccion" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-5">
                            <label>Localidad</label>
                            <input asp-for="Localidad" class="form-control" placeholder="Localidad" />
                            <span asp-validation-for="Localidad" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-5">
                            <div class="form-row">
                                <label>Telefono</label>
                                <input asp-for="Telefono" class="form-control" placeholder="Telefono" />
                                <span asp-validation-for="Telefono" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group col-md-5">
                            <label>Email</label>
                            <input asp-for="Email" class="form-control" placeholder="Email" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-row col-md-5">
                            <div class="form-group col-md-6">
                                <label>Estado</label>
                                <select asp-for="Estado" class="form-control">
                                    <option value="true">Activo</option>
                                    <option value="false">Inactivo</option>
                                </select>
                            </div>
                        </div>

                    </div>


                </div>
                <div class="modal-footer">
                    <a type="button" class="btn btn-primary" href="~/Clientes">Cerrar</a>
                    <button type="submit" class="btn btn-success">Guardar Cambios</button>
                </div>
            </form>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />

} 

Views/Clientes/Delete.cshtml
@model MvcClientes.Models.Cliente

@{
    ViewData["Title"] = "Eliminar Cliente";
}

<h1 class="text-primary">Eliminar Carrier</h1>

<h3 class="text-secondary">Esta seguro que desea eliminar el carrier?</h3>
<div>
    <h4>Carrier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |  <a href="~/Clientes" type="button" class="btn btn-primary">Volver a la lista de carriers</a>
        <div>
            
        </div>
    </form>
  
</div>

Views/Clientes/Details.cshtml
@model MvcClientes.Models.Cliente

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4 class="text-secondary">Carriers</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Localidad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |  <a href="~/Clientes" type="button" class="btn btn-primary">Volver a la lista de Clientes</a>

</div>

Views/Clientes/Edit.cshtml
@model MvcClientes.Models.Cliente

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-primary">Editar</h1>

<h4 class="text-secondary">Carrier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localidad" class="control-label"></label>
                <input asp-for="Localidad" class="form-control" />
                <span asp-validation-for="Localidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Estado" /> @Html.DisplayNameFor(model => model.Estado)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="~/Clientes" type="button" class="btn btn-primary">Volver a la lista de Carriers</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clientes/Index.cshtml
@model IEnumerable<MvcClientes.Models.Cliente>


@{
    ViewData["Title"] = "Index";
}




<div class="row" style="width:100%">
    <div class="col-6">
        <h2 class="text-primary">Lista de Carriers</h2>
    </div>
    <div class="col-4 text-right">
    </div>
</div>



<p>
    <a asp-action="Create" asp-controller="Clientes" class="btn btn-info">Crear Nuevo Carrier</a>
</p>
<div class="p-4 border rounded bg-light">
    <table class="table table-bordered table-responsive-xl">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Direccion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Localidad)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefono)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Localidad)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefono)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.Email)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Detalle</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <h1 class="display-4">Gestion de Ecom</h1>
  
</div>

Views/Productos/Create.cshtml
@model MvcClientes.Models.Productos

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="width:100%">
    <div class="col-6">
        <h2 class="text-primary">Agregar Nuevo Producto</h2>
    </div>
</div>




<form method="post" enctype="multipart/form-data">
    <div class="modal-body">
        <div style="padding-left:15%;padding-right:15%;padding-bottom:30px "></div>
        <div class="row p-3 border-0">
            <!--si hay un error en el modelo va a salir reflejado en el detalle-->
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>
        <div class="form-row" style="padding-top:14px;">
            <div class="form-group col-md-6">
                <label>Nombres</label>
                <input asp-for="Nombre" class="form-control" placeholder="Nombres" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label>Descripcion</label>
                <input asp-for="Descripcion" class="form-control" placeholder="Descripcion" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group col-md-5">
                <label>Imagen</label>
                <input asp-for="Imagen" class="form-control" placeholder="Imagen" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group col-md-5">
                <label>Precio</label>
                <input asp-for="Precio" class="form-control" placeholder="Precio" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            </div>

        </div>



    <div class="modal-footer">
        <a type="button" class="btn btn-primary" href="~/Productos">Cerrar</a>
        <button type="submit" class="btn btn-success">Guardar Cambios</button>
    </div>
</form>



@section Scripts {
    <partial name="_ValidationScriptsPartial" />

} 

Views/Productos/Delete.cshtml
@model MvcClientes.Models.Productos

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Eliminar Producto</h1>

<h3 class="text-secondary">Esta seguro que desea eliminar el Producto?</h3>

<div>
    <h4>Productos</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> | <a href="~/Productos" type="button" class="btn btn-primary">Volver a la lista de Productos</a>
        <div>

        </div>
    </form>
</div>

Views/Productos/Details.cshtml
@model MvcClientes.Models.Productos

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Detalle</h1>

<div>
    <h4 class="text-secondary">Productos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |  <a href="~/Productos" type="button" class="btn btn-primary">Volver a la lista de Productos</a>

</div>

Views/Productos/Edit.cshtml
@model MvcClientes.Models.Productos

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-primary">Editar</h1>

<h4 class="text-secondary">Productos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="~/Productos" type="button" class="btn btn-primary">Volver a la lista de Productos</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcEccom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcEccom</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ml-auto">
                        <!--
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>
        -->
                        <li class="navbar-brand mx-0 mx-lg-1"><a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Carriers</a>
                        </li>
                        <li class="navbar-brand mx-0 mx-lg-4"><a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcEccom - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>